name: CMake on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository including all submodules (recursive)
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Ensure CMake installed
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      # Setup Vulkan SDK
      - name: Install Vulkan SDK
        id: vulkan
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: latest
          cache: true

      # Configure CMake
      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DVULKAN_SDK=${{env.VULKAN_SDK}}
          -G "Visual Studio 17 2022"

      # Build
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Run Tests
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}